import string

#######################################
# CONSTANTS
#######################################

DIGITS = '0123456789'
LOWER_LETTERS = string.ascii_lowercase
UPPER_LETTERS = string.ascii_uppercase
LETTERS = string.ascii_letters
LETTERS_DIGITS = LETTERS + DIGITS
LABEL_CHARS = LETTERS + '_' + DIGITS
STOP_CHARS = LETTERS_DIGITS + '\n\r(),_'

MEM_DEPTH = 1024
WORD_WIDTH = 32
OP_CODE_PAD_SIZE = 6
REG_PAD_SIZE = 5
IMM_PAD_SIZE = 16
BR_ADDR_PAD_SIZE = 21
ABS_ADDR_PAD_SIZE = 26
UNUSED_PAD_SIZE = 11
ADDR_PAD_SIZE = len(format(MEM_DEPTH-1, 'X'))
WORD_PAD_SIZE = len(format((2 ** WORD_WIDTH)-1, 'X'))
TEXT_SEGMENT = 'text'
DATA_SEGMENT = 'data'

MAX_REGISTERS = 32
REGISTERS = [ 'R' + str(i) for i in range(MAX_REGISTERS)]
LINK_REGISTER = 31
READ_ONLY_REG = 'R0'

IMMEDIATE_EXPONENT = 16
IMM_MAX_UNSIGNED = (2 ** IMMEDIATE_EXPONENT) - 1
IMM_MIN_SIGNED = -1 * (2 ** (IMMEDIATE_EXPONENT-1))

MIF_PREAMBLE = f'''DEPTH = {MEM_DEPTH};
WIDTH = {WORD_WIDTH};
ADDRESS_RADIX = HEX;
DATA_RADIX = HEX;
CONTENT
BEGIN

'''

MIF_EPILOGUE = '\nEND;'